name: Fetch the register
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *' # 1AM every 1st of the month
jobs:
  scrape:
    name: Fetch the register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Fetch the data
        run: uv run scraper.py

      - name: Commit and push
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add data/*.json
          git commit -m 'Update the data and stats' || echo "Nothing to commit"
          git push
